INSERT INTO RRHH_PERSONA (NOMBRE, APELLIDOS, FECHA_NACIMIENTO) VALUES ('Pedro', 'García', '2010-01-01')
INSERT INTO RRHH_PERSONA (NOMBRE, APELLIDOS, FECHA_NACIMIENTO) VALUES ('Paco', 'Sanchez', '2010-01-01')
INSERT INTO RRHH_PERSONA (NOMBRE, APELLIDOS, FECHA_NACIMIENTO) VALUES ('Pedro', 'Alcantara', '2010-01-01')
INSERT INTO RRHH_PERSONA (NOMBRE, APELLIDOS, FECHA_NACIMIENTO) VALUES ('Sara', 'Baras', '2010-01-01')