INSERT INTO RRHH_PERSONA (NOMBRE, APELLIDOS, FECHA_NACIMIENTO, VALORACION_SERVICIO) VALUES ('Pedro', 'García', '2010-01-01', 7)
INSERT INTO RRHH_PERSONA (NOMBRE, APELLIDOS, FECHA_NACIMIENTO, VALORACION_SERVICIO) VALUES ('Paco', 'Sanchez', '2010-01-01', 6)
INSERT INTO RRHH_PERSONA (NOMBRE, APELLIDOS, FECHA_NACIMIENTO, VALORACION_SERVICIO) VALUES ('Pedro', 'Alcantara', '2010-01-01', 3)
INSERT INTO RRHH_PERSONA (NOMBRE, APELLIDOS, FECHA_NACIMIENTO, VALORACION_SERVICIO) VALUES ('Sara', 'Baras', '2010-01-01',9)